# Generated by Django 6.0.2 on 2026-02-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_book_added_by_alter_book_book_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_creator',
            field=models.BooleanField(default=False, help_text='Designates whether this user can upload books.'),
        ),
    ]
